Lecture 3/hw
goodprofy/react-2024-01-15 pull request #3
Opened 2024-01-28 18:25 UTC by goodprofy

2024-01-30 11:02 UTC, SArchieEdu requested changes
Лучше пока упростить, мы еще будем проходить и мемо, и useMemo, useCallback, renderProps и тд. Давайте подождем этих тем, чтобы сразу учитывать нюансы

2024-01-30 11:02 UTC, SArchieEdu commented on src/components/Restaurants/Restaurants.tsx
> +  }, [] as ComponentProps<typeof Tabs>["tabs"]);
это скорее map

2024-01-30 11:02 UTC, SArchieEdu commented on src/components/Restaurants/Restaurants.tsx
> +    });
это скорее логика места выбора, а не самой табы. Табы обычно показывает то, что передали, что логично

2024-01-30 12:41 UTC, goodprofy commented on src/components/Button/Button.tsx
> +const ButtonInner: FC<Props> = ({
@SArchieEdu затрудняюсь дать название компоненту который позже будет обернут в memo. На примере forwardRef добавляю Forwarded, получилось бы ButtonForwarded, но с memo писать ButtonMemoized когда она не memoized не получается. Вы что пишите?

2024-01-30 12:53 UTC, goodprofy commented on src/components/DishAmount/DishAmount.tsx
> +  }, []);
@SArchieEdu тут все линейно, так что скорее вред, я решил завернуть на будущее) Завернул в useMemo потому что useCallback это useMemo, зачем регать много useCallback когда можно только 1 useMemo. Профит от этого есть, опять же если зависимости соблюдаются, т.е если ф-й 10, и одна из зависимостей нужна только для 1 ф-и, то ф-ю лучше вынести из useMemo в useCallback с этой зависимостью, а из useMemo зависимость убрать.

2024-01-30 12:59 UTC, goodprofy commented on src/components/Flex/Flex.tsx
> +export const Flex: FC<PropsWithChildren<Props>> = ({
@SArchieEdu вы имеете ввиду что вместо тупых таких компонентов нужно писать глобальные стили(tailwindcss использовать, он мне не нравится)? Возможно у меня травмы после ReactNative, я даже думал прикрутить их генератор стилей для web https://stylexjs.com/, но он всю кучу вываливает в паблик, сложно сплитить - отказался.

2024-01-30 13:02 UTC, goodprofy commented on src/components/Input/Input.tsx
> +};
@SArchieEdu обработка event, так же не люблю в них передавать value(или то что часто меняется, обычно value это внутренний state), но пока забил, стили позже будут.

2024-02-05 15:32 UTC, SArchieEdu commented on src/components/Button/Button.tsx
> +const ButtonInner: FC<Props> = ({
Я бы не стал оборачивать в мемо)

2024-02-05 15:35 UTC, SArchieEdu commented on src/components/DishAmount/DishAmount.tsx
> +  }, []);
давайте пока не будем мемоизировать для оптимизации, пока не дойдем до оптимизации, сейчас это скорее ухудшает читабельность, чем улучшает работу

2024-02-05 15:36 UTC, SArchieEdu commented on src/components/Flex/Flex.tsx
> +export const Flex: FC<PropsWithChildren<Props>> = ({
не надо тэилвинд, просто по месту можно в стилях напистаь display: flex и тд

2024-02-05 15:36 UTC, SArchieEdu approved these changes

2024-02-06 06:27 UTC, merged